Refactor(plugins): Move jinja filter code for arista.avd.add_md_toc to PyAVD
aristanetworks/avd pull request #4104
Opened 2024-06-12 08:52 UTC by gmuloc

## Change Summary

Move jinja filter code for arista.avd.add_md_toc to PyAVD

## Related Issue(s)

Fixes #<ISSUE ID>

## Component(s) name

`arista.avd.add_md_toc`

## Proposed changes

Moving the code and unit tests for arista.avd.add_md_toc  filter to PyAVD

## How to test

Refactored pytest + things should break

## Checklist

### Repository Checklist

- [x] My code has been rebased from devel before I start
- [x] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [x] My change requires a change to the documentation and documentation have been updated accordingly.
- [x] I have updated [molecule CI](https://github.com/aristanetworks/avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly. (check the box if not applicable)

2024-06-12 09:09 UTC, ClausHolbechArista requested changes

2024-06-12 09:09 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/plugins/filter/add_md_toc.py
> +    convert_dicts = RaiseOnUse(
```suggestion
    add_md_toc = RaiseOnUse(
```

2024-06-13 05:25 UTC, ClausHolbechArista approved these changes

2024-06-13 07:27 UTC, Shivani-gslab commented on python-avd/pyavd/j2filters/add_md_toc.py
> +    str
```suggestion
    str:
```

2024-06-13 13:12 UTC, Vibhu-gslab approved these changes

2024-06-14 06:02 UTC, merged