Fix(eos_designs)!: Remove eBGP LAN outbound route-map for WAN
aristanetworks/avd pull request #4107
Opened 2024-06-12 09:42 UTC by gmuloc

## Change Summary

The shipped in eBGP LAN feature is mot working for connected and static redistributed inside a VRF as the route-map would not match these routes. Similarly the routes coming from an eBGP peering in any VRF (including default) would be blocked out by the RM-BGP-UNDERLAY-PEERS-OUT route-map.

This PR is a breaking change to fix this situation.

## Related Issue(s)

Discovered while working on #3720 and following review comments, separated in its own PR in order to be able to communicate with clarity about the breaking change.

## Component(s) name

`arista.avd.eos_design`

## Proposed changes

* Removing the outbound route-map for eBGP LAN peers on WAN routers
* Editing doc
* Adding limitation for eBGP peering in `network_services` received routes in VRF default that would not be advertised to the WAN.

## How to test

molecule + test on existing lab

## Checklist

### Repository Checklist

- [x] My code has been rebased from devel before I start
- [x] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [x] My change requires a change to the documentation and documentation have been updated accordingly.
- [x] I have updated [molecule CI](https://github.com/aristanetworks/avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly. (check the box if not applicable)

2024-06-12 10:14 UTC, ClausHolbechArista approved these changes
So we are breaking the experimental HA behavior with this. But we have the real HA PR incoming so that is fine for me.

2024-06-12 15:08 UTC, carlbuchmann requested changes
We should add a comment in the release notes about this breaking change.

2024-06-14 08:52 UTC, ClausHolbechArista approved these changes
Two minor comments to the release-notes

2024-06-14 08:52 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/docs/release-notes/4.x.x.md
> +To keep the broken route-map, structured_configuration can be used.
```suggestion
To keep the broken route-map, `structured_config` can be used.
```

2024-06-14 08:52 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/docs/release-notes/4.x.x.md
> +For all these reasons, the route-map is being removed.
```suggestion
For these reasons, the route-map was removed as a bug fix.
```

2024-06-14 12:16 UTC, carlbuchmann approved these changes
LGTM

2024-06-14 12:16 UTC, merged