Cut: Remove deprecated deploy_to_cv role
aristanetworks/avd pull request #4609
Opened 2024-10-17 12:13 UTC by gmuloc

## Change Summary

Role was deprecated in 4.x and planned for removal in 5.x

## Component(s) name

`arista.avd.deploy_to_cv`

## Proposed changes

Removing the role (there is no process for this in Ansible, only for plugins)

## Checklist

### Repository Checklist

- [x] My code has been rebased from devel before I start
- [x] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [x] My change requires a change to the documentation and documentation have been updated accordingly.
- [x] I have updated [molecule CI](https://github.com/aristanetworks/avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly. (check the box if not applicable)

2024-10-17 12:31 UTC, carlbuchmann commented on ansible_collections/arista/avd/docs/porting-guides/5.x.x.md
> +The following deprecared ansible roles have been removed from the `arista.avd` Ansible collection in v5.0.0.
```suggestion
The following deprecated Ansible roles have been removed from the `arista.avd` Ansible collection in v5.0.0.
```

2024-10-17 12:31 UTC, carlbuchmann commented on ansible_collections/arista/avd/docs/release-notes/5.x.x.md
> +The following deprecated ansible role has been removed from the `arista.avd` Ansible collection in v5.0.0.
```suggestion
The following deprecated Ansible role has been removed from the `arista.avd` Ansible collection in v5.0.0.
```

2024-10-17 12:32 UTC, carlbuchmann approved these changes
LGTM

2024-10-17 20:00 UTC, alexeygorbunov approved these changes
LGTM.
Also confirmed with molecule's `cv_deploy` scenario

2024-10-18 05:43 UTC, ClausHolbechArista requested changes

2024-10-18 05:43 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/meta/runtime.yml
>            The module will be redirected automatically until AVD version 5.0.0 after which it will be removed.
```suggestion
```

2024-10-18 05:57 UTC, ClausHolbechArista approved these changes

2024-10-18 05:57 UTC, merged