Feat(pyavd): Add _source to AvdBase type
aristanetworks/avd pull request #4838
Opened 2024-12-20 15:31 UTC by gmuloc

## Change Summary

## Related Issue(s)

Fixes #<ISSUE ID>

## Component(s) name

`arista.avd.<role-name>`

## Proposed changes

## How to test

## Checklist

### User Checklist

- N/A

### Repository Checklist

- [ ] My code has been rebased from devel before I start
- [ ] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [ ] My change requires a change to the documentation and documentation have been updated accordingly.
- [ ] I have updated [molecule CI](https://github.com/aristanetworks/avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly. (check the box if not applicable)

2025-02-20 15:18 UTC, ClausHolbechArista requested changes

2025-02-20 15:18 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/molecule/eos_designs_negative_unit_tests/inventory/host_vars/connected-endpoints-monitor-session-connected-endpoint-acl.yml
> +  for servers[0 (name=INDIVIDUAL_1)].adapters[0].
For indexed lists let's keep the old style of `[<primary_key>=<value>]`

2025-02-20 15:18 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/molecule/eos_designs_negative_unit_tests/inventory/host_vars/failure-connected-endpoint-parent-port-profile-does-not-exist.yml
> +  Profile 'THIS-PROFILE-DOES-NOT-EXIST' applied under port profile 'port_profiles[0 (profile=PROFILE-1)]' does not exist in 'port_profiles'.
Somehow we should have a reference to `parent_profile`. Either in the path or just in the text.

2025-02-20 15:18 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/molecule/eos_designs_negative_unit_tests/inventory/host_vars/failure-network-port-ptp-profile-does-not-exist.yml
> +  PTP Profile 'THIS-PROFILE-DOES-NOT-EXIST' referenced under 'network_ports[0]' does not exist in 'ptp_profiles'.
"referenced under" here, "applied under" in other tests, and "defined under" in some as well. If we add the full path (including the `.profile` key maybe it should be "referenced in".

2025-02-20 15:18 UTC, ClausHolbechArista commented on python-avd/pyavd/_schema/models/avd_indexed_list.py
> +                if cls.__name__.startswith("Dynamic")
This feels hacky.

2025-02-20 15:18 UTC, ClausHolbechArista commented on python-avd/pyavd/_schema/models/avd_model.py
> +    _field_source: ClassVar[dict[str, InputPath]] = {}
This should not be a classvar but an instance var. Having it as a class var would maintain a single dict across all instances.

2025-02-20 15:18 UTC, ClausHolbechArista commented on python-avd/pyavd/_schema/models/avd_model.py
> +        cls_instance._source = data_source
The _source could be set in the same way as `_custom_data` so you can just add it to the cls_args.

2025-02-20 15:18 UTC, ClausHolbechArista commented on python-avd/pyavd/_schema/models/avd_model.py
> +    def get_field_source(self, key: str) -> str:
Here you are not prefixing with underscore like we do for all the other methods. This could clash with a model field (if we ever had one with get_ :)

2025-02-20 15:18 UTC, ClausHolbechArista commented on python-avd/pyavd/_schema/models/avd_model.py
> +        # TODO: discuss if we should include the item path in error messages so that if the field come from a profile we
yeah we probably need something like `via` or similar. Also when we later add code sources or files.

2025-02-20 15:18 UTC, ClausHolbechArista commented on python-avd/pyavd/_schema/models/avd_model.py
> +        new_instance._source = self._source
I would have expected something similar on merge, inherit etc.

2025-02-20 15:18 UTC, ClausHolbechArista commented on python-avd/pyavd/_schema/models/avd_model.py
> +            cls._field_source[field] = child_data_source
I don't think this would work well. Setting it on the class. A list of classes would break quickly.

2025-02-24 14:29 UTC, gmuloc commented on python-avd/pyavd/_schema/models/avd_indexed_list.py
> +                if cls.__name__.startswith("Dynamic")
any better suggestion? :)

2025-02-26 13:26 UTC, gmuloc commented on python-avd/pyavd/_schema/models/avd_model.py
> +    def get_field_source(self, key: str) -> str:
yeah will change - it is just that tehn ruff if sad when we use the function outside of the class :)

2025-02-26 13:39 UTC, gmuloc commented on python-avd/pyavd/_schema/models/avd_model.py
> +            cls._field_source[field] = child_data_source
moved to the instance

2025-02-26 15:16 UTC, gmuloc commented on ansible_collections/arista/avd/molecule/eos_designs_negative_unit_tests/inventory/host_vars/failure-network-port-ptp-profile-does-not-exist.yml
> +  PTP Profile 'THIS-PROFILE-DOES-NOT-EXIST' referenced under 'network_ports[0]' does not exist in 'ptp_profiles'.
addressed

2025-02-26 15:16 UTC, gmuloc commented on python-avd/pyavd/_schema/models/avd_model.py
> +    _field_source: ClassVar[dict[str, InputPath]] = {}
done

2025-02-26 15:17 UTC, gmuloc commented on python-avd/pyavd/_schema/models/avd_model.py
> +        cls_instance._source = data_source
done

2025-02-26 15:23 UTC, gmuloc commented on python-avd/pyavd/_schema/models/avd_indexed_list.py
> +                if cls.__name__.startswith("Dynamic")
Added a TODO for now - we need to refactor this forward

2025-05-02 10:20 UTC, ClausHolbechArista commented
moving to draft since I believe this one is not done yet. At least all tests are failing :)

2026-05-04 15:55 UTC, gmuloc commented
this should be revisited once we move more tracking into pyavd-utils

2026-05-04 15:55 UTC, closed without merging